### ISSUE TITLE
Incompatible with base-4.11

### ISSUE THREAD

**Issue by nomeata** [int-index/ether#39]
I was about to try `ether`, but I am using `base-4.11`, so it does not yet seem to be available to me.

**Comment by int-index** [comment]
GHC doesn't know how to optimize `ether` code properly, generating numerous useless instance specializations. It causes memory consumption at least quadratic in the amount of transformer layers.

At work we were hitting 64 GiB memory limit on our build machines, due to use of `ether`. It could only be solved by `-fno-specialize` (I don't remember the exact flag name), which is very unsatisfactory.

You can observe this even when compiling the `ether` test suite .

Because of this, I no longer use `ether` and don't actively maintain it. So you're welcome to make it work with newer `base` and I'll upload a new version on Hackage, but your time will be better spent with a different effect system :)

**Comment by nomeata** [comment]
Thanks for the warning. Maybe you want to mark the package as deprecated on hackage? You can do that without uploading a new package, on this link: http://hackage.haskell.org/package/ether/maintain

**Comment by int-index** [comment]
Alright, I marked it as deprecated. Thanks for the suggestion.

**Comment by int-index** [comment]
Thanks for investigating this @4e6, and it's good news that with newer GHC using `ether` at scale is possible!

However, I'm still unable to guarantee that I will allocate enough time to its maintenance. If you'd like to become a maintainer of `ether` I'll grant you commit rights on GitHub and upload rights on Hackage.

**Comment by 4e6** [comment]
Regarding the issue. Please add the revision with updated bounds:

```
base >=4.9 && <4.12
```

Nothing else needs to be changed. It already compiles with ghc-8.4.1; tested with `nightly-2018-04-05` Stackage resolver
